# This file stores configurations for your Shopify app.

client_id = "44770e333ebb5a3f6dacd7a15906f455"
name = "Herbal Healers Ops"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_inventory,write_inventory,read_locations,read_publications,write_publications,read_orders,read_reports,read_customers,write_customers"

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/api/webhooks/app_scopes_update"

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/app_uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_data_request"
  compliance_topics = [ "customers/data_request"]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/customers_redact"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "/api/webhooks/shop_redact"
  compliance_topics = [ "shop/redact" ]
